import React from 'react';
import {ScrollView, StyleSheet, Text, TouchableOpacity, View} from 'react-native';

function HomeScreen({onOpenGigs}) {
  return <ScrollView style={styles.container} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><View><Text style={styles.eyebrow}>TUESDAY, 25 AUGUST</Text><Text style={styles.title}>Good morning, Aarav</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>AM</Text></View></View><View style={styles.hero}><Text style={styles.heroKicker}>YOUR CAMPUS, YOUR CRAFT</Text><Text style={styles.heroTitle}>What can you make happen today?</Text><Text style={styles.heroBody}>Three new briefs match your skills.</Text><TouchableOpacity style={styles.heroButton} onPress={onOpenGigs}><Text style={styles.heroButtonText}>See opportunities  →</Text></TouchableOpacity></View><View style={styles.sectionHead}><Text style={styles.sectionTitle}>Quick start</Text><Text style={styles.sectionLink}>View all</Text></View><View style={styles.quickGrid}>{[['✦', 'Offer a skill', 'Earn from what you know'], ['⌕', 'Find a collaborator', 'Build something together']].map(item => <TouchableOpacity style={styles.quickCard} key={item[1]}><Text style={styles.quickIcon}>{item[0]}</Text><Text style={styles.quickTitle}>{item[1]}</Text><Text style={styles.quickBody}>{item[2]}</Text></TouchableOpacity>)}</View><View style={styles.sectionHead}><Text style={styles.sectionTitle}>For you</Text><Text style={styles.sectionLink}>Refresh</Text></View>{[['Brand identity for a café', 'Design · 2 days ago', '₹1,800'], ['Event highlight reel', 'Video · 5 days ago', '₹2,400']].map(item => <TouchableOpacity key={item[0]} style={styles.brief}><View style={styles.briefIcon}><Text style={styles.briefIconText}>✦</Text></View><View style={styles.briefInfo}><Text style={styles.briefTitle}>{item[0]}</Text><Text style={styles.briefMeta}>{item[1]}</Text></View><Text style={styles.briefPrice}>{item[2]}</Text></TouchableOpacity>)}</ScrollView>;
}

const styles = StyleSheet.create({container: {flex: 1, backgroundColor: '#F4F8F7'}, content: {padding: 22, paddingBottom: 30}, header: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24}, eyebrow: {color: '#D47C43', fontSize: 10, fontWeight: '900', letterSpacing: 1.4}, title: {color: '#123B43', fontSize: 24, fontWeight: '900', marginTop: 6}, avatar: {width: 44, height: 44, borderRadius: 22, backgroundColor: '#123B43', alignItems: 'center', justifyContent: 'center'}, avatarText: {color: '#FFF', fontWeight: '900'}, hero: {backgroundColor: '#123B43', borderRadius: 22, padding: 20, overflow: 'hidden'}, heroKicker: {color: '#E9B872', fontSize: 10, fontWeight: '900', letterSpacing: 1.3}, heroTitle: {color: '#FFFDF8', fontSize: 26, lineHeight: 30, fontWeight: '900', marginTop: 12, maxWidth: 270}, heroBody: {color: '#B9D1CD', fontSize: 14, marginTop: 9}, heroButton: {alignSelf: 'flex-start', backgroundColor: '#E9B872', borderRadius: 11, paddingHorizontal: 13, paddingVertical: 10, marginTop: 18}, heroButtonText: {color: '#123B43', fontSize: 12, fontWeight: '900'}, sectionHead: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 28, marginBottom: 13}, sectionTitle: {color: '#123B43', fontSize: 18, fontWeight: '900'}, sectionLink: {color: '#D47C43', fontSize: 12, fontWeight: '900'}, quickGrid: {flexDirection: 'row', gap: 11}, quickCard: {flex: 1, backgroundColor: '#FFFDF8', borderRadius: 16, padding: 15, minHeight: 124, borderWidth: 1, borderColor: '#E0E9E6'}, quickIcon: {color: '#D47C43', fontSize: 23}, quickTitle: {color: '#123B43', fontWeight: '900', fontSize: 14, marginTop: 12}, quickBody: {color: '#71827D', fontSize: 11, lineHeight: 16, marginTop: 4}, brief: {backgroundColor: '#FFFDF8', borderRadius: 15, padding: 13, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#E0E9E6', marginBottom: 10}, briefIcon: {width: 40, height: 40, borderRadius: 12, backgroundColor: '#F8E7D4', alignItems: 'center', justifyContent: 'center', marginRight: 11}, briefIconText: {color: '#D47C43', fontSize: 18}, briefInfo: {flex: 1}, briefTitle: {color: '#274B4D', fontSize: 13, fontWeight: '900'}, briefMeta: {color: '#8A9995', fontSize: 11, marginTop: 4}, briefPrice: {color: '#123B43', fontSize: 13, fontWeight: '900'}});

export default HomeScreen;