import React from 'react';
import {KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, TouchableOpacity, View} from 'react-native';

function LoginScreen({onLogin, onRegister}) {
  return <KeyboardAvoidingView style={styles.container} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View><Text style={styles.kicker}>WELCOME BACK</Text><Text style={styles.title}>Good to see you.</Text><Text style={styles.subtitle}>Pick up where your next opportunity left off.</Text><TextInput placeholder="University email" placeholderTextColor="#8A9995" style={styles.input} keyboardType="email-address" autoCapitalize="none" /><TextInput placeholder="Password" placeholderTextColor="#8A9995" secureTextEntry style={styles.input} /><TouchableOpacity><Text style={styles.forgot}>Forgot password?</Text></TouchableOpacity><TouchableOpacity style={styles.primary} onPress={onLogin}><Text style={styles.primaryText}>Sign in  →</Text></TouchableOpacity></View><TouchableOpacity onPress={onRegister}><Text style={styles.footer}>New to SkillSwap? <Text style={styles.footerAction}>Create an account</Text></Text></TouchableOpacity></KeyboardAvoidingView>;
}

const styles = StyleSheet.create({container: {flex: 1, backgroundColor: '#F4F8F7', padding: 25, paddingTop: 70, justifyContent: 'space-between'}, kicker: {color: '#D47C43', fontSize: 11, fontWeight: '900', letterSpacing: 1.5}, title: {color: '#123B43', fontSize: 35, fontWeight: '900', marginTop: 9}, subtitle: {color: '#647773', fontSize: 15, lineHeight: 22, marginTop: 10, marginBottom: 28}, input: {height: 56, backgroundColor: '#FFFDF8', borderWidth: 1, borderColor: '#DCE8E4', borderRadius: 13, paddingHorizontal: 16, marginBottom: 12, color: '#123B43', fontSize: 15}, forgot: {color: '#D47C43', fontSize: 13, fontWeight: '800', textAlign: 'right', marginVertical: 8}, primary: {height: 56, backgroundColor: '#123B43', borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginTop: 16}, primaryText: {color: '#FFFDF8', fontSize: 15, fontWeight: '900'}, footer: {color: '#71827D', textAlign: 'center', fontSize: 14, marginBottom: 10}, footerAction: {color: '#123B43', fontWeight: '900'}});

export default LoginScreen;