import React from 'react';
import {SafeAreaView, StyleSheet, Text, TouchableOpacity, View} from 'react-native';

function WelcomeScreen({onGetStarted, onSignIn}) {
  return <SafeAreaView style={styles.container}><View><View style={styles.topLine}><View style={styles.miniMark}><Text style={styles.miniMarkText}>S</Text></View><Text style={styles.brand}>SkillSwap</Text></View><View style={styles.heroShape}><Text style={styles.heroIcon}>↗</Text><View style={styles.heroBadge}><Text style={styles.heroBadgeText}>Your skills have value</Text></View></View><Text style={styles.kicker}>THE STUDENT SKILLS MARKETPLACE</Text><Text style={styles.title}>Make your next move count.</Text><Text style={styles.subtitle}>Trade your talents, find great collaborators, and grow together on campus.</Text></View><View><TouchableOpacity style={styles.primary} onPress={onGetStarted}><Text style={styles.primaryText}>Create your account  →</Text></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={onSignIn}><Text style={styles.secondaryText}>I already have an account</Text></TouchableOpacity><Text style={styles.note}>Made for students who make things happen.</Text></View></SafeAreaView>;
}

const styles = StyleSheet.create({container: {flex: 1, backgroundColor: '#F4F8F7', padding: 25, paddingTop: 24, justifyContent: 'space-between'}, topLine: {flexDirection: 'row', alignItems: 'center'}, miniMark: {width: 34, height: 34, borderRadius: 11, backgroundColor: '#E9B872', alignItems: 'center', justifyContent: 'center'}, miniMarkText: {color: '#123B43', fontSize: 21, fontWeight: '900'}, brand: {color: '#123B43', fontSize: 19, fontWeight: '900', marginLeft: 9}, heroShape: {height: 220, borderRadius: 28, marginTop: 26, backgroundColor: '#123B43', justifyContent: 'center', alignItems: 'center', overflow: 'hidden'}, heroIcon: {color: '#E9B872', fontSize: 108, fontWeight: '200', transform: [{rotate: '-20deg'}]}, heroBadge: {position: 'absolute', right: 18, bottom: 18, backgroundColor: '#F4F8F7', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8}, heroBadgeText: {color: '#123B43', fontSize: 11, fontWeight: '900'}, kicker: {color: '#D47C43', fontSize: 11, fontWeight: '900', letterSpacing: 1.3, marginTop: 29}, title: {color: '#123B43', fontSize: 38, lineHeight: 42, fontWeight: '900', marginTop: 8, letterSpacing: -0.8}, subtitle: {color: '#647773', fontSize: 16, lineHeight: 23, marginTop: 12}, primary: {height: 56, borderRadius: 14, backgroundColor: '#D47C43', alignItems: 'center', justifyContent: 'center'}, primaryText: {color: '#FFFDF8', fontSize: 15, fontWeight: '900'}, secondary: {height: 54, borderRadius: 14, borderWidth: 1, borderColor: '#B9CCC7', alignItems: 'center', justifyContent: 'center', marginTop: 11}, secondaryText: {color: '#123B43', fontSize: 14, fontWeight: '900'}, note: {color: '#8A9995', fontSize: 11, textAlign: 'center', marginTop: 16}});

export default WelcomeScreen;